POST {{urlRoot}}/api/Blog/AddBlog HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0ZXN0LnVzZXJAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3RhbmRhcmRVc2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJ0ZXN0LnVzZXJAZ21haWwuY29tIiwiZXhwIjoxNjY3MjI2ODI4LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MTgzLyIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcxODMvIn0.NiKkzq2e8gldPEmJOudua1mkXI6wRqtZltCKzgh-3Hc
Content-Type: application/json

{
  "name": "",
  "description": "",
  "content": "",
  "tags": [""]
}